### ISSUE TITLE
Should timeline idle times be striped?

### ISSUE THREAD

**Issue by keitharm** [gabriel-discord/gabriel-ui#30]
You can make out idle time the way it is, but would it be better if it was striped as well?
![image](https://user-images.githubusercontent.com/919806/100910593-c97a3b80-3493-11eb-8df5-556f0b346840.png)
![image](https://user-images.githubusercontent.com/919806/100910619-d008b300-3493-11eb-8e20-d23c7257e255.png)

**Comment by jfwu90** [comment]
`react-apexcharts` allows specifying pattern to get the slanted lines, but unfortunately it doesn't allow setting fill pattern with a function the way it does with colors.

https://apexcharts.com/docs/options/fill/

Closing the issue since it's not possible with the current implementation.

If you add in support in apexcharts, then I'll add it to gabriel.
https://github.com/apexcharts/apexcharts.js/blob/e9e7fefc7fcd5d94b6ad23eda3e19da07d250a83/src/modules/Fill.js#L116
